//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageProcessing.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BIPStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BIPStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageProcessing.Languages.BIPStrings", typeof(BIPStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap must be at least 2 inches wide!.
        /// </summary>
        public static string BitmapMustBeAtLeast2InchesWide_STR {
            get {
                return ResourceManager.GetString("BitmapMustBeAtLeast2InchesWide_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t analyze image.
        /// </summary>
        public static string CanTAnalyzeImage_STR {
            get {
                return ResourceManager.GetString("CanTAnalyzeImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create 1 bit/pixel JPEG file!.
        /// </summary>
        public static string CanTCreate1BitPixelJPEGFile_STR {
            get {
                return ResourceManager.GetString("CanTCreate1BitPixelJPEGFile_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create bitmap from present parameters!.
        /// </summary>
        public static string CanTCreateBitmapFromPresentParameters_STR {
            get {
                return ResourceManager.GetString("CanTCreateBitmapFromPresentParameters_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find &apos;IDAT&apos; chunk! The file.
        /// </summary>
        public static string CanTFindIDATChunkTheFile_STR {
            get {
                return ResourceManager.GetString("CanTFindIDATChunkTheFile_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t generate bitmap.
        /// </summary>
        public static string CanTGenerateBitmap_STR {
            get {
                return ResourceManager.GetString("CanTGenerateBitmap_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get image properties from file!.
        /// </summary>
        public static string CanTGetImagePropertiesFromFile_STR {
            get {
                return ResourceManager.GetString("CanTGetImagePropertiesFromFile_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open image! .
        /// </summary>
        public static string CanTOpenImage_STR {
            get {
                return ResourceManager.GetString("CanTOpenImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove page from 2-page image!.
        /// </summary>
        public static string CanTRemovePageFrom2PageImage_STR {
            get {
                return ResourceManager.GetString("CanTRemovePageFrom2PageImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resize bitmap! .
        /// </summary>
        public static string CanTResizeBitmap_STR {
            get {
                return ResourceManager.GetString("CanTResizeBitmap_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save bitmap to stream.
        /// </summary>
        public static string CanTSaveBitmapToStream_STR {
            get {
                return ResourceManager.GetString("CanTSaveBitmapToStream_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t sharpen 1 bit per pixel image!.
        /// </summary>
        public static string CanTSharpen1BitPerPixelImage_STR {
            get {
                return ResourceManager.GetString("CanTSharpen1BitPerPixelImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construct Pages First!.
        /// </summary>
        public static string ConstructPagesFirst_STR {
            get {
                return ResourceManager.GetString("ConstructPagesFirst_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve has less than 2 points!.
        /// </summary>
        public static string CurveHasLessThan2Points_STR {
            get {
                return ResourceManager.GetString("CurveHasLessThan2Points_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in file.
        /// </summary>
        public static string ErrorInFile_STR {
            get {
                return ResourceManager.GetString("ErrorInFile_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        public static string Extreme_STR {
            get {
                return ResourceManager.GetString("Extreme_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger region must be inside image clip!.
        /// </summary>
        public static string FingerRegionMustBeInsideImageClip_STR {
            get {
                return ResourceManager.GetString("FingerRegionMustBeInsideImageClip_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger region size is zero!.
        /// </summary>
        public static string FingerRegionSizeIsZero_STR {
            get {
                return ResourceManager.GetString("FingerRegionSizeIsZero_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from disk.
        /// </summary>
        public static string FromDisk_STR {
            get {
                return ResourceManager.GetString("FromDisk_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF file is corrupted!.
        /// </summary>
        public static string GIFFileIsCorrupted_STR {
            get {
                return ResourceManager.GetString("GIFFileIsCorrupted_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        public static string Histogram_STR {
            get {
                return ResourceManager.GetString("Histogram_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file is corrupted!.
        /// </summary>
        public static string ImageFileIsCorrupted_STR {
            get {
                return ResourceManager.GetString("ImageFileIsCorrupted_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image path to .
        /// </summary>
        public static string ImagePathTo_STR {
            get {
                return ResourceManager.GetString("ImagePathTo_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter used!.
        /// </summary>
        public static string InvalidParameterUsed_STR {
            get {
                return ResourceManager.GetString("InvalidParameterUsed_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is either corrupted or it is not PNG file.!.
        /// </summary>
        public static string IsEitherCorruptedOrItIsNotPNGFile_STR {
            get {
                return ResourceManager.GetString("IsEitherCorruptedOrItIsNotPNGFile_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is incorrect!.
        /// </summary>
        public static string IsIncorrect_STR {
            get {
                return ResourceManager.GetString("IsIncorrect_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message code: .
        /// </summary>
        public static string MessageCode_STR {
            get {
                return ResourceManager.GetString("MessageCode_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Range.
        /// </summary>
        public static string MinRange_STR {
            get {
                return ResourceManager.GetString("MinRange_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Range R: .
        /// </summary>
        public static string MinRangeR_STR {
            get {
                return ResourceManager.GetString("MinRangeR_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Extreme.
        /// </summary>
        public static string NdExtreme_STR {
            get {
                return ResourceManager.GetString("NdExtreme_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image was loaded!.
        /// </summary>
        public static string NoImageWasLoaded_STR {
            get {
                return ResourceManager.GetString("NoImageWasLoaded_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize: Can&apos;t allocate bitmap.
        /// </summary>
        public static string ResizeCanTAllocateBitmap_STR {
            get {
                return ResourceManager.GetString("ResizeCanTAllocateBitmap_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing 1: There is not sufficient memory to resize file! Required:.
        /// </summary>
        public static string Resizing1ThereIsNotSufficientMemoryToResize_STR {
            get {
                return ResourceManager.GetString("Resizing1ThereIsNotSufficientMemoryToResize_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing 2: There is not sufficient memory to resize file! Required: .
        /// </summary>
        public static string Resizing2ThereIsNotSufficientMemoryToResize_STR {
            get {
                return ResourceManager.GetString("Resizing2ThereIsNotSufficientMemoryToResize_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory or file doesn&apos;t exist!.
        /// </summary>
        public static string SourceDirectoryOrFileDoesnTExist_STR {
            get {
                return ResourceManager.GetString("SourceDirectoryOrFileDoesnTExist_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are already 2 fingers located!.
        /// </summary>
        public static string ThereAreAlready2FingersLocated_STR {
            get {
                return ResourceManager.GetString("ThereAreAlready2FingersLocated_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are already 2 pages in the image!.
        /// </summary>
        public static string ThereAreAlready2PagesInTheImage_STR {
            get {
                return ResourceManager.GetString("ThereAreAlready2PagesInTheImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough memory to open bitmap from file.
        /// </summary>
        public static string ThereIsNotEnoughMemoryToOpenBitmapFromFile_STR {
            get {
                return ResourceManager.GetString("ThereIsNotEnoughMemoryToOpenBitmapFromFile_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not sufficient memory to open file.
        /// </summary>
        public static string ThereIsNotSufficientMemoryToOpenFile_STR {
            get {
                return ResourceManager.GetString("ThereIsNotSufficientMemoryToOpenFile_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is only 1 page in the image!.
        /// </summary>
        public static string ThereIsOnly1PageInTheImage_STR {
            get {
                return ResourceManager.GetString("ThereIsOnly1PageInTheImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        public static string Threshold_STR {
            get {
                return ResourceManager.GetString("Threshold_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiff image with Jpeg compression is not supported in GDI+ !.
        /// </summary>
        public static string TiffImageWithJpegCompressionIsNotSupported_STR {
            get {
                return ResourceManager.GetString("TiffImageWithJpegCompressionIsNotSupported_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total allocated memory:.
        /// </summary>
        public static string TotalAllocatedMemory_STR {
            get {
                return ResourceManager.GetString("TotalAllocatedMemory_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured!.
        /// </summary>
        public static string UnexpectedErrorOccured_STR {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccured_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format!.
        /// </summary>
        public static string UnsupportedFileFormat_STR {
            get {
                return ResourceManager.GetString("UnsupportedFileFormat_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported image format!.
        /// </summary>
        public static string UnsupportedImageFormat_STR {
            get {
                return ResourceManager.GetString("UnsupportedImageFormat_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported pixel format!.
        /// </summary>
        public static string UnsupportedPixelFormat_STR {
            get {
                return ResourceManager.GetString("UnsupportedPixelFormat_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Tiff Compression!.
        /// </summary>
        public static string UnsupportedTiffCompression_STR {
            get {
                return ResourceManager.GetString("UnsupportedTiffCompression_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom must be equal or less than 1..
        /// </summary>
        public static string ZoomMustBeEqualOrLessThan1_STR {
            get {
                return ResourceManager.GetString("ZoomMustBeEqualOrLessThan1_STR", resourceCulture);
            }
        }
    }
}
